services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NITRO_PORT: 3000
      NITRO_HOST: 0.0.0.0
      NUXT_PUBLIC_SITE_URL: ${NUXT_PUBLIC_SITE_URL:-https://randomix.vercel.app}
    restart: unless-stopped
